version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - my-network
    volumes:
      - mongodb:/data/db
      - ./scripts/products.json:/products.json
      - ./scripts/init-data.js:/init-data.js
      - ./scripts/mongo-init.sh:/mongo-init.sh
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 5s
      retries: 10
      timeout: 10s
    entrypoint: [ "bash", "mongo-init.sh" ]

  eshop:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: eshop 
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/products?directConnection=true&authSource=products

networks:
  my-network:
    name: my-network

volumes:
  mongodb:
